### ISSUE TITLE
Request: Give commits a description

### ISSUE THREAD

**Issue by bkevelham** [soupday/cc3_unity_tools_HDRP#18]
Dear Victor,

I'm trying to switch from CC's own Unity import tools to your much more comprehensive implementation. However, to follow along with your frequent updates, it would be nice if you could use actual commit messages, rather than just a future release number. That would make it a lot easier to see what has been changed, and whether or not that's immediately relevant to us. 

Just a suggestion. Keep up the excellent work. 

Bart.

**Comment by soupday** [comment]
The commits are a mess I'll grant you that.

I mostly just use the commit summary to label what files have been changed for that version.

I'm trying to keep three separate versions in sync, that all use the same code but have different material and shader assets and different dependencies. Figuring out the logistics of that has been a challenge and the commits tend to ping pong between the versions. Now that all three versions are more or less in the same place, it should be easier to keep track.
