### ISSUE TITLE
Incorrect texture assignment due to multiple texture search matches

### ISSUE THREAD

**Issue by bkevelham** [soupday/cc3_unity_tools_HDRP#19]
# What happened

When importing a CC model with several hair meshes, one of the meshes looked significantly different from the CC3 original. See the hair on top in the image below. 

![hairtextureassignmentbug](https://user-images.githubusercontent.com/46000002/138451662-64ce69b2-ac6c-4096-8cf7-156838aa04e0.png)

Upon further inspection it seems that after running the "Default" import process, an incorrect texture was assigned to one of the materials. (Texture assignment after first Unity import before running the tools was correct, and the json also contains the correct texture information). 

The culprit seems to be [`FindTexture(string[] folders, string search)` ](https://github.com/soupday/cc3_unity_tools_HDRP/blob/main/Editor/Util.cs#L330) or rather how Unity returns the search results. 

The search string in this particular case is `Hair_Transparency_Pbr_Diffuse`, which for the given folders returns the following results in this order:

- BabyHair_Transparency_Pbr_Diffuse
- Hair_Transparency_Pbr_Diffuse

When testing the first search result, the `EndsWith` verification succeeds, causing it to pick the incorrect texture. Given that I don't understand the complete logic behind the code, or the reason for a search rather than using exact paths from the original material, I won't suggest a fix. But if a search is required, perhaps there needs to be some form of a "best match" process for cases like these. Unity's search functionality seems to be incoherent at the best of times 😆 . 

As a quick local fix, replacing `EndsWith` with an `Equals` check instead, seems to resolve my issues, but perhaps that's a bad idea for reasons I'm not aware of. 

If you need further info or if you would like to have a copy of the model I used let me know. I could share that privately. (Given that they are CC store assets it's probably best not to share them here publicly). 

# Version Info

- Unity: 2021.1.17f1
- HDRP: 11.0.0
- CC3 Unity Tools: 0.1.8b

**Comment by soupday** [comment]
It's a throwback to the original Blender add-on, where there was no Json data to tell me where to look so I had to make educated guesses where to search for them...

Just like all the EndsWith comparisons, I think I was comparing texture paths with texture names originally and it got left in. Not 100% sure why I threw away the exact texture path to search for just the name. 

The texture lookups now try to locate the exact path first before falling back to "Equals" texture searches. This should resolve the problem.

**Comment by bkevelham** [comment]
It seems to be fix indeed. Thanks a bunch 👍
