### ISSUE TITLE
Emission texture slot missing on Skin Shader

### ISSUE THREAD

**Issue by Necka44** [soupday/cc3_unity_tools_HDRP#5]
Hello,

With SkinGen we can use emissive textures that can be applied anywhere on the body.
It seem that the Skin shaders in the CC3 Unity tool HDRP is missing the option to use Emissive texture.

Here is an example in CC3: 
![image](https://user-images.githubusercontent.com/39954105/127156227-8d5ed5e7-2f60-4ce7-b421-82fff4417457.png)

**Comment by soupday** [comment]
I'm always forgetting the emission maps...

I'll add it to the list.

**Comment by Necka44** [comment]
Thank you for adding it in the main release. It works perfectly and automatically set the glow texture (it doesn't take the original emission value into account but I don't care, I can define it myself in Unity it's actually perfect like this now)
