### ISSUE TITLE
Can't get the tool to actually work

### ISSUE THREAD

**Issue by Necka44** [soupday/cc3_unity_tools_HDRP#6]
Hello,

So at first I thought it was because I was using some character/clothing packages from CC store but now I can see that it's not the case.

Tested with Unity 2021.1.15 and Unity 2020.3.14 both using a **clean new project with HDRP sample**
Using Character Creator 3.43
Using CC3 Unity Tools 0.11

The character is a default CC3 female to which I applied a stylized skin I have, CC3 eyes from Human pack and standard CC3 clothing.

![image](https://user-images.githubusercontent.com/39954105/127181723-73c5afc6-9b87-480d-ac6e-d2d7ffbdfde4.png)

I exported the character following the instruction (Unity template, current pose, delete hidden face, merge hair etc.)

Once imported in Unity with the CC3 Tool this is the result:

![image](https://user-images.githubusercontent.com/39954105/127182028-dd8d4b59-c49f-4f24-8c99-ef5bc6c93701.png)
![image](https://user-images.githubusercontent.com/39954105/127182076-ffa273b7-2533-44d1-827f-f7c391e7d73b.png)

I might have a very gothic version of the tool because lots of things are black!

But where I'm highly surprised is that the clothing has more than just a black diffuse color issue, here is how it comes when I turn the material diffuse texture back to white:
![image](https://user-images.githubusercontent.com/39954105/127182420-b62de0ea-0a34-4350-8fe2-9668bbb7f29c.png)

![image](https://user-images.githubusercontent.com/39954105/127182589-3b701304-4b3d-43da-895f-6b8165f0df5d.png)

Teeth are also black, hair are black, everything is black.

It's extremely strange and despite testing the tool in many direction I can't seem to get it to work.
![image](https://user-images.githubusercontent.com/39954105/127182815-6e2762f6-fae7-435b-b627-d55d708440b5.png)

Oh I didn't mention it but as you can see the eyes are also broken

Would you have an idea on what's going on?

Edit:
I'm sorry I forgot also to mention that before using the CC3 tool, the FBX shows proper texturing (even though no normals, no nothing)
![image](https://user-images.githubusercontent.com/39954105/127183873-b3dd7c67-7d3e-4f6e-ae20-d64f9278e4ed.png)

**Comment by Necka44** [comment]
Update regarding clothing: Found that the tool change the texture tiling to 0, 0
![image](https://user-images.githubusercontent.com/39954105/127188060-8e90e241-ad98-40dd-9c03-596c5c7c0f68.png)

This is a strange behavior. On top of having the diffuse set to black on all other things as explained above

**Comment by soupday** [comment]
That's very odd. 

There's only one condition where the Tiling and Base Color would return (0,0) and Black, and that's if the JSON file was there, but it was empty, wrong or corrupt.

Does the <character name>.json file look right?

What happens if you delete the .json file and rebuild the advanced materials? (If there is no json file it will just go with default values for all the parameters, much like the Blender version.)

**Comment by Necka44** [comment]
It did that with multiple character export from CC to Unity, none worked, the Json files look ok but to be honest I don't know how it's supposed to look like. 

I can't attach .json here so I copied the content into a word document:
[test3.docx](https://github.com/soupday/cc3_unity_tools_HDRP/files/6887471/test3.docx)

I'm not sure what you meant with rebuild advanced materials? did you mean re-click on the tool "high quality" button? in that case nothing changes.

Actually I even tried to open the tool, delete the json file, click on "high quality" and the result is the same. Meaning that when I do it with a Json file it just ignores it I guess

I really have no clue on what's going on. I just updated CC to 3.43 but I doubt it's related.

It's really sad.. I was looking so much forward using this tool

Could it be my hierarchy? I think it's like yours on the screenshots of the documentation:
![image](https://user-images.githubusercontent.com/39954105/127200516-eae4faa5-5e68-4110-a7c3-4643b145a731.png)

The other tests had a _ in their name so I tried without, it's named "Test3" maybe it's the number..I really have no clue on this one. I'll try without a number

**Comment by Necka44** [comment]
Ok so it's not the name, I did a plain and simple test:
Opened a default CC3 sample character from here:
![image](https://user-images.githubusercontent.com/39954105/127201214-ad74e664-1cf2-4617-a6b2-10a195d72375.png)

Exported it straight away, named it "Huntress" 
Dragged the Huntress folder into Unity, launched the CC3 Tools, clicked on High quality nothing else, and same results
![image](https://user-images.githubusercontent.com/39954105/127201444-a032531e-5a33-4436-979e-fcad69aa29f9.png)

Log looks good as always: 
![image](https://user-images.githubusercontent.com/39954105/127201485-5565b2ed-b3fa-4a69-bb4d-5e4cbd806558.png)

What would make the tool ignore the Json file?
I attached the Json file (in a zip) of this character here as you can easily reproduce the same character maybe something corrupts it but I don't think so, the file looks legit
[TestHuntress JSON.zip](https://github.com/soupday/cc3_unity_tools_HDRP/files/6887593/TestHuntress.JSON.zip)

**Comment by Necka44** [comment]
Just a thought.. had that with Cinemachine package from Unity  in the past. If the package was too deep in a subfolder on a computer because of whatever limitation, some problems occurred. Unity fixed that for Cinemachine some time ago.

Could it be because of the length of the folder name on my computer to reach the file?

The path in my case is like that: F:\Game Dev\01-Unity\00-Projects\CC Import HDRP Test\Assets\CharacterImporter\Huntress

**Comment by soupday** [comment]
The JSON files look right.
It's also finding the textures, as it's connect the Mask maps and the custom textures for the teeth, so something must be going wrong when it's reading the JSON asset for the texture offset and tiling and base color.

I'll try that exact path for a project.

**Comment by soupday** [comment]
It's not the path length or the filesnames...

I made a project with exactly the same path, exactly the same file names. Exported the huntress character and even used your JSON file instead of the one my CC3 generated: all worked with no problems...

![huntress](https://user-images.githubusercontent.com/79094830/127210721-7f56730e-e619-41ee-b66b-0c8c35f8001b.jpg)

So it's not that.

Only difference is I'm using 2020.3.9f1 here. So next is trying again with 2020.3.14.

**Comment by soupday** [comment]
In the event of being able to reproduce this, I will write in a whole bunch of checks for parsing and reading the values from the json and Debug.LogWarn() eveything that fails. Hopefully that will show what's going on.

**Comment by Necka44** [comment]
Yeah I also tried to do it within a project in C:\Unity\Project and that didn't help... at least that cross it out.

I don't get it. I'm usually not bad at troubleshooting but here it doesn't make sense to me. It's a clean Unity install, a clean project (Using HDRP Sample but I guess that works for you as well?)

It can't be the project settings as they are "clean" so it could only be Unity editor preference. But I didn't change anything there either.

The official Reallusion Unity Auto setup on 2019.3 was working so it was "reading" the Json file at least in that version.

I'm installing 2020.3.9 like the version you have now to try. Then I'll start digging a bit in your code but it's always a bit difficult to understand when you're not the one who wrote it up of course

**Comment by soupday** [comment]
It's a puzzle. I'm guessing it's just a string comparison / localization problem, maybe unicode conversion.

It's clearly reading in the Json correctly, otherwise it wouldn't get the (G3Plus) character generation as this **only** comes from the Json data. I think it fails where it has to match the object and material names to the names in the Json file.

In traversing a Json path, there was one direct "==" string comparison in my Json parser which I've replaced with an InvariantCultureIgnoreCase comparision which might be the culprit.

I've also put LogErrors when it fails to find the Json data for each Mesh, Object and Material it tries to set up.

If I'm right and Unity is just mangling the strings for the object and material names, then you should see errors for each Object and Material, but not for the initial Mesh data object or Json Data parse.

I've pushed these changes to the Dev branch of the repository. You should be able to download and install this.

**Comment by Necka44** [comment]
Ah well... I got excited and thought I'd at least see some debug logs but no.. nothing changed.
I removed version 0.11 and now have version 0.1.3 and I have absolutely nothing in the console when importing with the tool.

Speaking about localization I don't know if that has importance but I do have some specifics in Windows regional settings.
Windows language is set to English, but date, time, decimal etc. format to French. The decimal symbol is a coma: , 

I do know that it can create issues in some edge cases so I prefer to point it out

**Comment by Necka44** [comment]
That's fuc***g it
That was the problem!
Well it doesn't solve the issue per se as I do need the French format for my work as we don't use the same decimals and other things but at least the culprit was found

**Comment by soupday** [comment]
if it was looking for commas instead of decimal points, then all the string to float conversions would fail... which means the colors, offset and tiling would all return zero's...

**Comment by soupday** [comment]
Ok, first attempt to fix number conversion culture:

This is to force non specific culture for string to float conversion:

System.Globalization.NumberStyles style = System.Globalization.NumberStyles.Number;            
System.Globalization.CultureInfo culture = System.Globalization.CultureInfo.InvariantCulture;

float.TryParse(value, style, culture, out float tryFloat)


Pushed to dev branch.

**Comment by Necka44** [comment]
I'll try it out tomorrow I'm off for today, thanks a lot for your support though, that's really great

On another note: There is no Normal slider for skin materials. I noticed that my character which have normally a smooth skin has some weird normals around the eyes (not the micro-normals, those are nice), when removing the normal map it's ok but switch a lot of things off. I don't know if it uses a default generic normal map in that case, I will investigate first tomorrow what comes out of CC3 textures but in CC3 the skin is quite smooth for sure

**Comment by Necka44** [comment]
So, everything is working well now!
I do still have a normal issue with the head but I need to do more tests on that side with the original CC character first to see if it's not me who is creating the issue.

Your tool is remarkable. I see that the latest version also have a normal map slider and the emission textures (automatically imported as well!)

Thanks a lot for your help, I'll close this issue, in case I can't figure out the normal effect on the head I'll open a new issue focused on that
