### ISSUE TITLE
Wrong ASMDEF setting for Editor

### ISSUE THREAD

**Issue by Necka44** [soupday/cc3_unity_tools_HDRP#8]
Hello, 

the Assembly definition of the Editor folder is wrongly set and forbid doing a build of the project

Can you please make sure the Editor checkbox is set on:
com.soupday.cc3_unity_tools.editor.asmdef

![image](https://user-images.githubusercontent.com/39954105/129444094-b6764283-e033-421b-9e12-9829b516717a.png)

**Comment by soupday** [comment]
Good catch, guess I should have tried to build something before now.

I've set the .asmdef for the package editor code to be only included for the editor, along with a few shader fixes in version 0.1.5.
